name: interception_smoothing
channels:
  - defaults
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - python=3.9
  - jupyter=1.0.0
  - jupyter_contrib_nbextensions=0.5.1
  - pip=21.2.4
  - numpy=1.20.3
  - scikit-learn=0.24.2
  - seaborn=0.11.1
  - statsmodels=0.12.2
  - ogb=1.3.3
  - pip:
          - external/sparse_smoothing
